# Generated by Django 5.0.6 on 2024-11-22 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity in grams')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('calories', models.FloatField(editable=False)),
                ('protein', models.FloatField(editable=False)),
                ('carbs', models.FloatField(editable=False)),
                ('fats', models.FloatField(editable=False)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.fooditem')),
            ],
        ),
    ]
